apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-net-ca
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-net-ca
  chart:
    git: git@github.com:sajidhz1/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: supplychain-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplychain-admin
    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://127.0.0.1:8200
      authpath: supplychain-net-auth
      secretcert: baf/crypto/ordererOrganizations/supplychain-net/ca?ca.supplychain-net-cert.pem
      secretkey: baf/crypto/ordererOrganizations/supplychain-net/ca?supplychain-net-CA.key
      secretadminpass: baf/credentials/supplychain-net/ca/supplychain?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: orderer
