apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-net-ca
  chart:
    git: git@github.com:sajidhz1/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: carrier-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://127.0.0.1:8200
      authpath: carrier-net-auth
      secretcert: baf/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: baf/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: baf/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
